# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ResourceViewer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'ObjectMapper', :git => 'https://github.com/Hearst-DD/ObjectMapper.git', :branch => 'swift-4'

  target 'ResourceViewerTests' do
    inherit! :search_paths
    pod 'ObjectMapper', :git => 'https://github.com/Hearst-DD/ObjectMapper.git', :branch => 'swift-4'
  end

  target 'ResourceViewerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
