# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QSMobileTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QSMobileTest
  		pod 'RxSwift'
  		pod 'RxCocoa'
  		pod 'SwiftyJSON'
        pod 'Former'



  target 'QSMobileTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
