# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mobile-test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mobile-test

  target 'mobile-testTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mobile-testUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'Alamofire'

end
