def rx_swift
  pod 'RxSwift', '~> 4'
end

def rx_cocoa
  pod 'RxCocoa', '~> 4'
end

def test_pods
  # pod 'RxTest', '~> 4'
  # pod 'RxBlocking', '~> 4'
end

target 'Domain' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Domain
  rx_swift

  target 'DomainTests' do
    inherit! :search_paths
    # Pods for testing
    test_pods
  end

end

target 'NetworkPlatform' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for NetworkPlatform
  rx_swift
  pod 'Alamofire'
  pod 'RxAlamofire'

  target 'NetworkPlatformTests' do
    inherit! :search_paths
    # Pods for testing
    test_pods
  end

end

target 'QuickSeriesTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  rx_cocoa
  rx_swift
  pod 'RxDataSources', '~> 3.1.0'

  use_frameworks!
  # Pods for QuickSeriesTest 
  pod 'SDWebImage/WebP'
  pod 'NVActivityIndicatorView'

  target 'QuickSeriesTestTests' do
    inherit! :search_paths
    # Pods for testing
    test_pods
  end

  target 'QuickSeriesTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
