workspace 'Quickseries'
platform :ios, '12.2'
use_frameworks!


target 'Quickseries-iOS' do
  project 'Quickseries-iOS/Quickseries-iOS.xcodeproj'
  
  pod 'Kingfisher', '~> 5.0'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'RxRelay', '~> 5'
  pod 'SnapKit', '~> 5.0.0'
  pod 'PhoneNumberKit', '~> 2.6'
  pod 'Moya', '~> 13.0'

  target 'Quickseries-iOSTests' do
    inherit! :search_paths
  end
  target 'Quickseries-iOSUITests' do
    inherit! :search_paths
  end
end
