# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QuickSeries' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod ‘RealmSwift’
  pod 'SDWebImage', '~> 4.0'
  pod 'ObjectMapperAdditions/Realm'
  pod 'SDWebImage', '~> 4.0'

  target 'QuickSeriesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QuickSeriesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
